# Generated by Django 4.2.16 on 2025-05-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0003_remove_user_age_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_products',
            field=models.ManyToManyField(blank=True, related_name='joined_users', to='products.depositproduct'),
        ),
    ]
